const IP_ADDRESS = process.env.IP_ADDRESS;

const PORT = process.env.PORT;

const SWAGGER_URL = process.env.SWAGGER_URL;

const ENCRYPTION_KEY = process.env.ENCRYPTION_KEY;

const DB_URL = process.env.DB_URL;

const DB_LOGS_URL = process.env.DB_LOGS_URL;

const PATH_ODEP_USER = process.env.PATH_ODEP_USER;

const PATH_ODEP_PROSUMER = process.env.PATH_ODEP_PROSUMER;

const PATH_ODEP_REGULATOR = process.env.PATH_ODEP_REGULATOR;

const PATH_ODEP_ASSET = process.env.PATH_ODEP_ASSET;

const PATH_ODEP_ASSETTYPE = process.env.PATH_ODEP_ASSETTYPE;

const PATH_ODEP_OFFER = process.env.PATH_ODEP_OFFER;

const PATH_ODEP_REQUEST = process.env.PATH_ODEP_REQUEST;

const PATH_ODEP_CONTRACT = process.env.PATH_ODEP_CONTRACT;

module.exports = {
    IP_ADDRESS,
    PORT,
    SWAGGER_URL,
    ENCRYPTION_KEY,
    DB_URL,
    DB_LOGS_URL,
    PATH_ODEP_USER,
    PATH_ODEP_PROSUMER,
    PATH_ODEP_REGULATOR,
    PATH_ODEP_ASSET,
    PATH_ODEP_ASSETTYPE,
    PATH_ODEP_OFFER,
    PATH_ODEP_REQUEST,
    PATH_ODEP_CONTRACT
}
